name: Build and Push OR check-PR

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      board:
        description: "Board to Compile"
        type: choice
        required: true
        default: "M5Cardputer"
        options:
          - M5Cardputer
          - M5StickCPlus2
          - ESP32-S3
          - lilygo-t-embed-cc1101

permissions:
  contents: write

jobs:
  compile_sketch:
    name: Build ${{ matrix.board.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        board:
          - name: "ESP32-S3 - M5Cardputer"
            env: "m5stack-cardputer"
            partitions:
              bootloader_addr: "0x1000"

          - name: "ESP32-S3 - lilygo-t-embed-cc1101"
            env: "lilygo-t-embed-cc1101"
            partitions:
              bootloader_addr: "0x1000"

          - name: "ESP32 - M5StickCPlus2"
            env: "m5stack-cplus2"
            partitions:
              bootloader_addr: "0x1000"

          - name: "Headless: ESP32-S3"
            env: "esp32-s3-devkitc-1"
            partitions:
              bootloader_addr: "0x1000"

          - name: "CoreS3"
            env: "m5stack-cores3"
            partitions:
              bootloader_addr: "0x1000"

          - name: "Launcher based environment: CYD"
            env: "LAUNCHER_CYD-2432S028"
            partitions:
              bootloader_addr: "0x1000"

          - name: "ESP32-C5"
            env: "esp32-c5"
            partitions:
              bootloader_addr: "0x2000"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PlatformIO
        run: |
          pip install --upgrade pip
          pip install platformio requests esptool intelhex

      - name: Inject build metadata
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${GITHUB_SHA::7}"
          fi

          sed -i "s/-DBRUCE_VERSION=/-DBRUCE_VERSION='\"$VERSION\"' ; /g" platformio.ini
          sed -i "s/-DGIT_COMMIT_HASH='\"Homebrew\"'/\!echo '-DGIT_COMMIT_HASH=\\\\\\\\\"'\$\(git describe --always --dirty)'\\\\\\\\\"'/g" platformio.ini

          echo "===== platformio.ini ====="
          cat platformio.ini

      - name: Build firmware
        run: |
          platformio run -e ${{ matrix.board.env }}

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: Bruce-${{ matrix.board.env }}
          path: Bruce-*.bin
          retention-days: 5
          if-no-files-found: error

      - name: Commit and push firmware
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          mkdir -p firmware/${{ matrix.board.env }}

          mv Bruce-*.bin firmware/${{ matrix.board.env }}/

          git add firmware/
          git commit -m "build: firmware ${{ matrix.board.env }} ($GITHUB_SHA)" || echo "Nothing to commit"
          git push
